const LIVE_MODE = 'live';
const SANDBOX_MODE = 'sandbox';

const REQUEST_ENDPOINTS = {
  [LIVE_MODE]: 'https://www.secure11gw.ro/portal/cgi-bin/',
  [SANDBOX_MODE]: 'https://www.activare3dsecure.ro/teste3d/cgi-bin/'
};

const TRANSACTION_TYPE_PREAUTH = '0';
const TRANSACTION_TYPE_SALE = '21';
const TRANSACTION_TYPE_REVERSAL = '24';
const TRANSACTION_TYPE_PARTIAL_REFUND = '25';
const TRANSACTION_TYPE_FRAUD_REVERSAL = '26';

const STATUS_APPROVED_TRANSACTION = 0;
const STATUS_DUPLICATE_TRANSACTION = 1;
const STATUS_REJECTED_TRANSACTION = 2;
const STATUS_PROCESSING_ERROR = 3;

module.exports = {
  LIVE_MODE,
  SANDBOX_MODE,
  REQUEST_ENDPOINTS,
  TRANSACTION_TYPE_PREAUTH,
  TRANSACTION_TYPE_SALE,
  TRANSACTION_TYPE_REVERSAL,
  TRANSACTION_TYPE_PARTIAL_REFUND,
  TRANSACTION_TYPE_FRAUD_REVERSAL,
  STATUS_APPROVED_TRANSACTION,
  STATUS_DUPLICATE_TRANSACTION,
  STATUS_REJECTED_TRANSACTION,
  STATUS_PROCESSING_ERROR,
};
