const LIVE_MODE = 'live';
const SANDBOX_MODE = 'sandbox';

const REQUEST_ENDPOINTS = {
  [LIVE_MODE]: 'https://www.secure11gw.ro/portal/cgi-bin/',
  [SANDBOX_MODE]: 'https://www.activare3dsecure.ro/teste3d/cgi-bin/'
};

const TRANSACTION_TYPE_PREAUTH = '0';
const TRANSACTION_TYPE_PREAUTH_RECURRING = '0';
const TRANSACTION_TYPE_SALE = '21';
const TRANSACTION_TYPE_REVERSAL = '24';
const TRANSACTION_TYPE_PARTIAL_REFUND = '25';
const TRANSACTION_TYPE_FRAUD_REVERSAL = '26';
const TRANSACTION_TYPE_RECURRING = '171';

const TRANSACTION_REQ_FIELDS = {
  [TRANSACTION_TYPE_PREAUTH]: ['AMOUNT', 'CURRENCY', 'ORDER',
    'DESC', 'MERCH_NAME','MERCH_URL', 'MERCHANT', 'TERMINAL', 'EMAIL', 'TRTYPE',
    'COUNTRY', 'MERCH_GMT', 'TIMESTAMP', 'NONCE', 'BACKREF'],
  [TRANSACTION_TYPE_SALE]: ['ORDER', 'AMOUNT', 'CURRENCY', 'RRN',
    'INT_REF','TRTYPE', 'TERMINAL', 'TIMESTAMP', 'NONCE', 'BACKREF'],
};

const TRANSACTION_REQ_FIELDS_EXTRA = {
  [TRANSACTION_TYPE_PREAUTH_RECURRING]: ['RECUR_FREQ', 'RECUR_EXP'],
};

TRANSACTION_REQ_FIELDS[TRANSACTION_TYPE_REVERSAL] = TRANSACTION_REQ_FIELDS[TRANSACTION_TYPE_SALE];
TRANSACTION_REQ_FIELDS[TRANSACTION_TYPE_PARTIAL_REFUND] = TRANSACTION_REQ_FIELDS[TRANSACTION_TYPE_SALE];
TRANSACTION_REQ_FIELDS[TRANSACTION_TYPE_FRAUD_REVERSAL] = TRANSACTION_REQ_FIELDS[TRANSACTION_TYPE_SALE];

const TRANSACTION_RES_FIELDS = {
  [TRANSACTION_TYPE_PREAUTH]: ['TERMINAL', 'TRTYPE', 'ORDER',
    'AMOUNT', 'CURRENCY','DESC', 'ACTION', 'RC', 'MESSAGE', 'RRN',
    'INT_REF', 'APPROVAL', 'TIMESTAMP', 'NONCE'],
  [TRANSACTION_TYPE_SALE]: ['ACTION', 'RC', 'MESSAGE', 'TRTYPE',
    'AMOUNT','CURRENCY', 'ORDER', 'RRN', 'INT_REF', 'TIMESTAMP', 'NONCE'],
};

const TRANSACTION_RES_FIELDS_EXTRA = {
  [TRANSACTION_TYPE_PREAUTH_RECURRING]: ['RECUR_FREQ', 'RECUR_EXP'],
}

TRANSACTION_REQ_FIELDS[TRANSACTION_TYPE_REVERSAL] = TRANSACTION_RES_FIELDS[TRANSACTION_TYPE_SALE];
TRANSACTION_REQ_FIELDS[TRANSACTION_TYPE_PARTIAL_REFUND] = TRANSACTION_RES_FIELDS[TRANSACTION_TYPE_SALE];
TRANSACTION_REQ_FIELDS[TRANSACTION_TYPE_FRAUD_REVERSAL] = TRANSACTION_RES_FIELDS[TRANSACTION_TYPE_SALE];

const STATUS_APPROVED_TRANSACTION = 0;
const STATUS_DUPLICATE_TRANSACTION = 1;
const STATUS_REJECTED_TRANSACTION = 2;
const STATUS_PROCESSING_ERROR = 3;

module.exports = {
  LIVE_MODE,
  SANDBOX_MODE,
  REQUEST_ENDPOINTS,
  TRANSACTION_TYPE_PREAUTH,
  TRANSACTION_TYPE_PREAUTH_RECURRING,
  TRANSACTION_TYPE_SALE,
  TRANSACTION_TYPE_REVERSAL,
  TRANSACTION_TYPE_PARTIAL_REFUND,
  TRANSACTION_TYPE_FRAUD_REVERSAL,
  TRANSACTION_TYPE_RECURRING,
  TRANSACTION_REQ_FIELDS,
  TRANSACTION_REQ_FIELDS_EXTRA,
  TRANSACTION_RES_FIELDS,
  STATUS_APPROVED_TRANSACTION,
  STATUS_DUPLICATE_TRANSACTION,
  STATUS_REJECTED_TRANSACTION,
  STATUS_PROCESSING_ERROR,
};
